spring.application.name=Exo12

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/orders_db
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.r2dbc.pool.max-acquire-time=2000ms
spring.r2dbc.pool.max-idle-time=30m
spring.r2dbc.pool.max-life-time=2h

spring.sql.init.mode=always
spring.sql.init.platform=postgresql

